### ISSUE TITLE
tag v2.4.10

### ISSUE THREAD

**Issue by ktdreyer** [ceph/mod-proxy-fcgi#3]
During the package review for EPEL (at https://bugzilla.redhat.com/1182770 ) the reviewer noted that although this module is "2.4.10", there's no tag in GitHub for this.

What do you think we should do for version numbering?

Should we tag 78a587f2bb4ad9a14c41301fd1b10853266ea6f1 as 2.4.10 ? And the future releases can be "2.4.10.1", "2.4.10.2", etc? Or something else entirely?

**Comment by yehudasa** [comment]
@ktdreyer pushed the v2.4.10 tag upstream, points at the specificed commit. Is that ok?

**Comment by ktdreyer** [comment]
Thanks! looks good.
