### ISSUE TITLE
unix socket

### ISSUE THREAD

**Issue by lpalgarvio** [ceph/mod-proxy-fcgi#4]
Hello

I'm having difficulty with getting unix sockets to work with ProxyPass and ProxyPassMatch.
Has this feature been backported?

`<LocationMatch ".+\.ph(p[345]?|t|tml)$">`
`# with tcp`
`#ProxyPassMatch "fcgi://127.0.0.1:9000/var/www/default/public_html/$1"`
`# with socket`
`ProxyPassMatch "unix:/var/run/php-fpm/php-fpm.sock|fcgi://localhost/var/www/default/public_html/$1"`
`</LocationMatch>`

https://httpd.apache.org/docs/trunk/mod/mod_proxy_fcgi.html

**Comment by yehudasa** [comment]
@lpalgarvio sadly this cannot be backported without modifying apache itself (the change requires changes to both apache and mod-proxy-fcgi).
