### ISSUE TITLE
Make a note that apxs is required

### ISSUE THREAD

**Issue by jtreminio** [ceph/mod-proxy-fcgi#7]
First time compiling for Apache - stumbled for a few minutes before realizing `apxs` is required to compile this!

**Comment by ktdreyer** [comment]
What distro are you using? Trying to think of how to word the instructions...

**Comment by jtreminio** [comment]
I'm on CentOS, `yum install httpd-devel`.

On Debian/Ubuntu it's `apt-get install apache2-dev`

**Comment by ktdreyer** [comment]
We could adjust the `AC_PATH_PROG(APXS, 'apxs')` check in `configure.ac` to print these package names when apxs is not found.

**Comment by ktdreyer** [comment]
See the PR at #8

**Comment by ktdreyer** [comment]
Also, if you're on CentOS, you can try the `mod_proxy_fcgi` package from EPEL, https://dl.fedoraproject.org/pub/epel/6/x86_64/repoview/mod_proxy_fcgi.html

I've updated the README for this in #9

**Comment by ktdreyer** [comment]
Fixed in #8 and #9
